appName: "Tricount"
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: "jdbc:h2:mem:dev"
  jpa:
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  mail:
    host: "smtp.univ-lille.fr"
    port: 587
    username: "leopold.hubert.etu@univ-lille.fr"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true